[package]
name = "leftpad"
version = "1.0.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]
license = "BSD-2-Clause"
description = "Pad a string to the left"
repository = "https://github.com/hfiguiere/leftpad-rs"
keywords = [ "string" ]

[dependencies]
